name: Run the integration tests

on:
    push:
        branches:
            - main

jobs:
  integrationtests:
    runs-on: ubuntu-latest
    env:
      MYSQL_ROOT_PASSWORD: root # default root password to use must be 'root'
      TEST_DB_HOST: '127.0.0.1'
      TEST_DB_PORT: '3306'
      TEST_DB_DATABASE: share_a_meal
      TEST_DB_USER: root
      TEST_DB_PASSWORD: root
      NODE_ENV: test
    services:
      mysql:
        image: mysql:5.7
        ports:
          - '3306'
    steps:
      - uses: actions/checkout@main

      - name: Start MySQL connection from host
        run: |
          sudo /etc/init.d/mysql start
          sudo apt-get install -y mysql-client
          mysql -uroot -p${{ env.MYSQL_ROOT_PASSWORD }} -e "SHOW DATABASES;"
          mysql -uroot -p${{ env.MYSQL_ROOT_PASSWORD }} -e "CREATE DATABASE ${{env.TEST_DB_DATABASE}};"

      - name: Import database script
        run: |
          mysql -uroot -p${{env.MYSQL_ROOT_PASSWORD}} ${{env.TEST_DB_DATABASE}} < share-a-meal.sql
          mysql -uroot -p${{env.MYSQL_ROOT_PASSWORD}} ${{env.TEST_DB_DATABASE}} -e "SHOW TABLES;"

      - name: npm install
        run: |
          npm install

      - name: npm test
        run: |
          npm test -- --DB_PASSWORD {{env.MYSQL_ROOT_PASSWORD}} --TEST_DB_USER root --TEST_DB_NAME ${{env.TEST_DB_DATABASE}}

